import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({children}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <Header />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;