import type { Metadata } from "next";
import "./globals.css";
import SearchInput from "@/app/ui/SearchInput";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({children}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={"antialiased"}
      >
        <SearchInput />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;